name: Playwright Tests All Browsers
on:
  workflow_dispatch:
  schedule:
      # “At minute 0 at 12 AM (GMT+7) on every day-of-week from Monday through Friday.”
      - cron: 0 17 * * 1-5
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  All-browsers-test:
    runs-on: ubuntu-latest
    env:
      # ENV keys specific to this job - KEEP THEM HERE
      TEST_URL: ${{ secrets.TEST_URL }}
      MAIN_PAGE_TITLE: ${{ secrets.MAIN_PAGE_TITLE }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      SEARCH_TEST: ${{ secrets.SEARCH_TEST }}
    steps:
    - name: Use the reusable Playwright test action
      uses: ./.github/actions/run-playwright-tests@v1
      with:
        test_command: ui-test-all
