name: Playwright Google Chrome Tests
on:
  workflow_dispatch:
jobs:
  Google-chrome-test:
    runs-on: ubuntu-latest
    env:
      # ENV keys specific to this job - KEEP THEM HERE
      TEST_URL: ${{ secrets.TEST_URL }}
      MAIN_PAGE_TITLE: ${{ secrets.MAIN_PAGE_TITLE }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      SEARCH_TEST: ${{ secrets.SEARCH_TEST }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Use the reusable Playwright test action
      uses: ./.github/actions/run-playwright-tests@v1
      with:
        test_command: ui-test-google-chrome
